// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe0TExep0Ewyr4vM4sF_Pa0W2QPIG-P60',
    appId: '1:321818567146:web:fd6af72f929af426a71293',
    messagingSenderId: '321818567146',
    projectId: 'pameyaan',
    authDomain: 'pameyaan.firebaseapp.com',
    storageBucket: 'pameyaan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO6DwtvAIRuNbX92pVgMJTYfUjlxry-Lw',
    appId: '1:321818567146:android:f1e3ed9c95b409cea71293',
    messagingSenderId: '321818567146',
    projectId: 'pameyaan',
    storageBucket: 'pameyaan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeYkOPELnIdzW7tpeo4HMdlgiM0nG8SC0',
    appId: '1:321818567146:ios:c6dcb928cd896701a71293',
    messagingSenderId: '321818567146',
    projectId: 'pameyaan',
    storageBucket: 'pameyaan.firebasestorage.app',
    iosBundleId: 'com.example.pemeyaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeYkOPELnIdzW7tpeo4HMdlgiM0nG8SC0',
    appId: '1:321818567146:ios:c6dcb928cd896701a71293',
    messagingSenderId: '321818567146',
    projectId: 'pameyaan',
    storageBucket: 'pameyaan.firebasestorage.app',
    iosBundleId: 'com.example.pemeyaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe0TExep0Ewyr4vM4sF_Pa0W2QPIG-P60',
    appId: '1:321818567146:web:bd7949891694b267a71293',
    messagingSenderId: '321818567146',
    projectId: 'pameyaan',
    authDomain: 'pameyaan.firebaseapp.com',
    storageBucket: 'pameyaan.firebasestorage.app',
  );
}
